name: generate metrics for profile

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  # don't forget to change if you're using 'master' branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-metrics
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Options
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata, achievements
          repositories: ${{ github.repository }}
          repository_visibility: all
          repository_forks: include
          repository_affiliations: owner,collaborator,organization_member
          commits_authoring: include
          commits_ownership: include
          issues_authoring: include
          issues_ownership: include
          pull_requests_authoring: include
          pull_requests_reviewing: include
          discussions_authoring: include
          discussions_answering: include
          # Achievements settings
          plugin_achievements: yes
          plugin_achievements_threshold: S
          plugin_achievements_secrets: true
          plugin_achievements_display: compact
          plugin_achievements_limit: 10
          plugin_achievements_sort: S
          # Output settings
          output: output